name: Pre Image Package
on: workflow_dispatch
jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'chg86'
          password: 'dckr_pat_JJlc9e4YURPGnidjrUCMDin6UwQ'

      - name: Build and push production images
        uses: docker/build-push-action@v5
        with:
          tags: chg86/bkci-docker:v1.0.4
          push: true
